[package]
name = "descriptor_metadata_research"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bdk_wallet = { path = "../../..", features = ["std", "elias-fano", "test-utils"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "restoration"
harness = false

[patch.crates-io]
bdk_chain = { path = "../../../../bdk/crates/chain" }
bdk_core = { path = "../../../../bdk/crates/core" }
